//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calculationform
    {
        public string empname { get; set; }
        public Nullable<decimal> Basicsalary { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> netsalary { get; set; }
    }
}
